---------------1--------------ICEBERG.CLTIENE_360_ESTUDIANTES ---------------------
--- ORDEN_CUN (UNICOS)  -----  NUMERO_DOCUMENTO (DUPLICADOS) ---------- REFERENCIA_PAGO 


SELECT  TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM ICEBERG.CLTIENE_360_ESTUDIANTES 
                WHERE ESTADO_FINANCIACION = ''1''
                AND ORDEN_CUN = ''2914403''
                ---AND NUMERO_DOCUMENTO = ''1192793902''
                ---AND REFERENCIA_PAGO = ''100293686''
                 
                ')

--------------2--------------- ICEBERG.CLTIENE_360_RESPUESTA ---------------------
--- ORDEN_CUN (UNICOS)  -----  NUMERO_DOCUMENTO_ESTUDIANTE (DUPLICADOS)

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM ICEBERG.CLTIENE_360_RESPUESTA 
             ---WHERE ORDEN_CUN = ''3132676''
             WHERE NUMERO_DOCUMENTO_ESTUDIANTE = ''1000032122''
             ---AND PERIODO = ''26V02''
              ')

                  

---------------3--------------ICEBERG.CUNT_TRAMITE_EXTERNO ---------------------
--- ORDEN  -----  IDENTIFICACION --------- ORDEN_INICIAL---

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM ICEBERG.CUNT_TRAMITE_EXTERNO
              WHERE ORDEN = ''2914403''
              ---AND IDENTIFICACION = ''1192793902''
               
                ')

--------------4---------------ICEBERG.CREDITO ---------------------
--- ORDEN (UNICOS)  -----  CLIENTE  -------------------------- 

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM ICEBERG.CREDITO 
          WHERE ORDEN = ''2914403''  
          ---REFERENCIA
          ---AND CLIENTE = ''1192793902''
                ')


---------------5--------------PORTAL_PAGOS_CUN.PPT_CUN_DETALLE_RESPUESTA_PAGO ---------------------
---   --- REFERENCIA (DUPLICADOS) --RECIBO_ICEBERG (20 DUPLICADOS)  

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM PORTAL_PAGOS_CUN.PPT_CUN_DETALLE_RESPUESTA_PAGO
                WHERE ORDEN = ''2914403''
                ---WHERE REFERENCIA = ''100293686''
                ---WHERE OBSERVACIONES_ICEBERG LIKE ''%2519483%''
                ')

---------------6--------------RECIBO_CAJA ---------------------
---- NUMERO (UNICOS, LLAVE RECIBO_ICEBERG) -------  CLIENTE ----------- PERIODO  

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM RECIBO_CAJA 
        WHERE ESTADO = ''V''  
        ----NUMERO = ''''
                ')

-------------7----------------CUNT_ALUMNOS_ORDENES_X_PERIODO ---------------------
--- ORDEN (UNICOS)  -----  DOC_ALUM  -------- CLIENTE ---------- PERIODO ---- PERIODO_ULT_PAGO --------- 

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM CUNT_ALUMNOS_ORDENES_X_PERIODO 
                WHERE ORDEN = ''2914403''


                ')

---------8--------ICEBERG.CLTIENE_360_DETALLE_CUOTAS----------------------
------------- ORDEN_CUN (DUPLICADOS) ------- REFERENCIA_PAGO (DUPLICADOS) ------------------------
SELECT TOP 10 *
FROM OPENQUERY([172.16.1.175], '
                ---SELECT CAST(ORDEN_CUN AS VARCHAR(100)) AS ORDEN_CUN, CAST(VALOR_CUOTA AS VARCHAR(100)) AS VALOR_CUOTA 
                SELECT *
                FROM ICEBERG.CLTIENE_360_DETALLE_CUOTAS
                WHERE ORDEN_CUN = ''2914403''
            ')
           
     

-------------9----------------ORDEN ---------------------
--- ORDEN (UNICOS)  -----  CLIENTE_SOLICITADO  ------------- 

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM ORDEN 
 WHERE ORDEN = ''2914403''
                
                ')

-------------10----------------LIQUIDACION_ORDEN ---------------------
--- ORDEN  -----  CLIENTE -------------------------- 

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM LIQUIDACION_ORDEN 
                WHERE ORDEN = ''2914403''
                ')

-----------------------------SINU.BAS_TERCERO ---------------------
  -----  NUM_IDENTIFICACION -------

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM SINU.BAS_TERCERO 
                
                ')

-----------------------------SINU.BAS_CEN_COSTO ---------------------
--- ----------------- COD_CEN_COSTO  --1P23300----- NUM_IDENTIFICACION --------------

SELECT TOP 10 * FROM OPENQUERY([172.16.1.175], '
                SELECT *
 FROM SINU.BAS_CEN_COSTO 
                
                ')

-------------------COLUMNS QUERY--------------------------

               SELECT * FROM OPENQUERY([172.16.1.175], '
    SELECT 
        COLUMN_ID AS ORDEN,
        COLUMN_NAME AS COLUMNA, 
        DATA_TYPE AS TIPO_DATO, 
        DATA_LENGTH AS LONGITUD
    FROM ALL_TAB_COLUMNS 
    WHERE OWNER = ''ICEBERG'' 
      AND TABLE_NAME = ''CLTIENE_360_ESTUDIANTES''
    ORDER BY COLUMN_ID
');


---------------------columnas respuesta cltiene----------------


 SELECT TOP 10 * 
 FROM CUN_REPOSITORIO.Financiera.Financiaciones_CTAYUDA_V2
 WHERE RES_GENERO_ESTUDIANTE IS NULL


 ---------------------------agregacion columnas caracterizacion respuesta360--------------
 ALTER TABLE Financiera.Financiaciones_CTAYUDA_V2
ADD RES_VALOR_CUOTA_INICIAL DECIMAL(18,2) NULL;

 ALTER TABLE Financiera.Financiaciones_CTAYUDA_V2 ADD RES_GENERO_ESTUDIANTE NVARCHAR(20) NULL;
ALTER TABLE Financiera.Financiaciones_CTAYUDA_V2 ADD RES_EDAD_ESTUDIANTE   INT          NULL;

-------------------------sp johan financiaciones--------------------


SELECT   top 10     IDENTIFICACION, [REFERENCIA DE PAGO], [TIPO DE IDENTIFICACIÓN], NOMBRE, [EMAIL INSTITUCIONAL], [EMAIL PERSONAL], CELULAR, TELÉFONO, DOCUMENTO, [ORDEN RPVI], [DOCUMENTO DE LA ORDEN INICIAL], 
                         [ORDEN INICIAL], [ESTADO ORDEN RPVI], PERIODO, [FECHA DE LA ORDEN], [FECHA DE APROBACIÓN CUOTA INI], [FECHA CREA ESTUDIANTE CLTIENE], [FECHA FIN DE PROCESO CLTIENE], [FECHA SOLICITUD DE CREDITO], 
                         [FECHA DE VENCIMIENTO DE ORDEN], MENSAJE, [CENTRO DE COSTO], [VALOR DE LA ORDEN], DESCRIPCION, GRUPO, FONDO, [FUENTE FUNCIÓN], [VALOR AVAL], [SERVIIO MÉDICO], VALOR_PAGADO, VALOR_ORDEN, 
                         VALOR_FINANCIADO, VALOR_PAGADO_EN_ICEBERG, [GASTOS TÉCNICOS], [PORCENTAJE DE INTERÉS], [ESTADO DE PAGO ESTUDIO], [¿TIENE PROCESO EN 360?], [¿TIENE PROCESO LEGALIZADO?], 
                         [¿ORDEN RPVI LIQUIDADA?], [¿ORDEN INICIAL LIQUIDADA?], OBSERVACION
FROM            OPENQUERY([172.16.1.175], 
                         '
SELECT
  B.NUM_IDENTIFICACION AS IDENTIFICACION,
  E.REFERENCIA_PAGO AS "REFERENCIA DE PAGO",
  B.TIP_IDENTIFICACION AS "TIPO DE IDENTIFICACIÓN",
  B.NOM_LARGO AS NOMBRE,
  B.DIR_EMAIL AS "EMAIL INSTITUCIONAL",
  B.DIR_EMAIL_PER AS "EMAIL PERSONAL",
  B.TEL_CECULAR AS CELULAR,
  B.TEL_RESIDENCIA AS "TELÉFONO",
  O.DOCUMENTO,
  O.ORDEN AS "ORDEN RPVI",
  T.DOCUMENTO AS "DOCUMENTO DE LA ORDEN INICIAL",
  T.ORDEN AS "ORDEN INICIAL",
  DECODE(ORD.ESTADO,''V'',''VIGENTE'',''A'',''ANULADA'',ORD.ESTADO) AS "ESTADO ORDEN RPVI",
  O.PERIODO,  
  O.FECHA_ORDEN AS "FECHA DE LA ORDEN",
  C.FECHA_PAGO AS "FECHA DE APROBACIÓN CUOTA INI",--FEC_APROB_CUOTA_INI_1,
  E.FEC_CREACION AS "FECHA CREA ESTUDIANTE CLTIENE",--FEC_ESTUDIANT_LISTO_2,
  M.FEC_CREACION AS "FECHA FIN DE PROCESO CLTIENE",--FEC_FINAL_3,
  R.FECHA_SOLICITUD AS "FECHA SOLICITUD DE CREDITO",--FEC_MARCA_PAGO_4,
  O.FECHA_VENCIMIENTO AS "FECHA DE VENCIMIENTO DE ORDEN",
  O.MENSAJE,  
  O.CENTRO_COSTO AS "CENTRO DE COSTO",
  O.VALOR_TOTAL AS "VALOR DE LA ORDEN",
  O.DESCRIPCION,  
  O.GRUPO,
  O.FONDO,  
  O.FUENTE_FUNCION AS "FUENTE FUNCIÓN",
  E.VALOR_AVAL AS "VALOR AVAL",
  E.SERVICIO_MEDICO AS "SERVIIO MÉDICO",
  E.VALOR_PAGADO,
  E.VALOR_MATRICULA AS VALOR_ORDEN,
  E.VALOR_FINANCIACION AS VALOR_FINANCIADO,
  C.VALOR VALOR_PAGADO_EN_ICEBERG,
  E.GASTOS_TECNICOS AS "GASTOS TÉCNICOS",
  E.PORCENTAJE_INTERES AS "PORCENTAJE DE INTERÉS",
  E.ESTADO_PAGO_ESTUDIO AS "ESTADO DE PAGO ESTUDIO",
  DECODE(E.NUMERO_DOCUMENTO,NULL,''NO'', ''SI'') AS "¿TIENE PROCESO EN 360?",
  DECODE(m.id,NULL,''NO'', ''SI'') AS "¿TIENE PROCESO LEGALIZADO?",
  DECODE(LR.LIQUIDACION,NULL, ''NO'', ''SI'') AS "¿ORDEN RPVI LIQUIDADA?",
  DECODE(LM.LIQUIDACION,NULL, ''NO'', ''SI'') AS "¿ORDEN INICIAL LIQUIDADA?",   
--  OP.EST_PAG_ACA AS "ESTADO PAGO DE LA ORDEN INI",  
  CASE WHEN E.NUMERO_DOCUMENTO IS NULL THEN '''' ELSE DECODE(E.ESTADO_FINANCIACION,1,''CREDITO COMPLETADO'',''CREDITO PENDIENTE CTAYUDA'') END OBSERVACION
  FROM
  ICEBERG.ORDEN O
  INNER JOIN SINU.BAS_TERCERO B ON B.NUM_IDENTIFICACION = TO_CHAR(O.CLIENTE_SOLICITADO)
  INNER JOIN SINU.BAS_CEN_COSTO CC ON CC.COD_CEN_COSTO = O.CENTRO_COSTO
  LEFT JOIN ICEBERG.CUNT_TRAMITE_EXTERNO T ON O.ORDEN = T.ORDEN_INICIAL
  LEFT JOIN ICEBERG.CREDITO R ON R.CLIENTE = B.NUM_IDENTIFICACION AND R.ORDEN = T.ORDEN AND OBSERVACIONES LIKE ''%CLTIENE%''
  LEFT JOIN ICEBERG.CLTIENE_360_ESTUDIANTES E ON E.NUMERO_DOCUMENTO = T.IDENTIFICACION AND E.ORDEN_CUN = T.ORDEN
  LEFT JOIN ICEBERG.CLTIENE_360_RESPUESTA M ON M.NUMERO_DOCUMENTO_ESTUDIANTE = E.NUMERO_DOCUMENTO AND M.ORDEN_CUN = E.ORDEN_CUN AND M.VALIDACION=1
  --LEFT JOIN ICEBERG.CLTIENE_360_RESPUESTA_TMP M ON M.NUMERO_DOCUMENTO_ESTUDIANTE = E.NUMERO_DOCUMENTO AND SUBSTR(M.MENSAJE,0,2)=''OK''
  LEFT JOIN PORTAL_PAGOS_CUN.PPT_CUN_DETALLE_RESPUESTA_PAGO D ON D.REFERENCIA = E.REFERENCIA_PAGO
  LEFT JOIN RECIBO_CAJA C ON C.NUMERO = D.RECIBO_ICEBERG AND C.estado=''V''
  LEFT JOIN CUNT_ALUMNOS_ORDENES_X_PERIODO OP ON OP.DOC_ALUM = TO_CHAR(O.CLIENTE_SOLICITADO) AND OP.ORDEN = T.ORDEN --AND 
  LEFT JOIN ORDEN ORD ON ORD.ORDEN = T.ORDEN_INICIAL and ORD.DOCUMENTO = T.DOCUMENTO_INICIAL
  LEFT JOIN LIQUIDACION_ORDEN LR ON LR.ORDEN = T.ORDEN_INICIAL AND LR.DOCUMENTO = T.DOCUMENTO_INICIAL
  LEFT JOIN LIQUIDACION_ORDEN LM ON LM.ORDEN = T.ORDEN AND LM.DOCUMENTO = T.DOCUMENTO
  WHERE
  O.DOCUMENTO=''RPVI''
  AND UPPER(O.DESCRIPCION) LIKE ''%CLTIENE%''
 --- AND B.NUM_IDENTIFICACION=''1032464561''
 ---AND o.periodo=''24V05''
  AND O.ESTADO=''V''
  ')